---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: cf-test-harness
- name: current-app-info

run:
  path: cf-test-harness/nodejs/ci/tasks/load-tests
