---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: cf-test-harness
- name: current-app-info

run:
  path: cf-test-harness/nodejs/ci/tasks/update-routes
