groups:
- name: main
  jobs:
  - unit-tests
  - deploy-app
  - load-tests
  - promote-new-version

resources:
- name: every-5m
  type: time
  source: {interval: 5m}

- name: cf-test-harness
  type: git
  source:
      uri: {{github-uri}}
      branch: {{github-branch}}


- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: every-5m
    trigger: true
  - get: cf-test-harness
    trigger: true
  - task: run-unit-tests
    file: cf-test-harness/nodejs/ci/tasks/unit-tests.yml

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: cf-test-harness
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: cf-test-harness/nodejs/ci/tasks/current-app-get-info.yml
    params:
      CF_API: {{cf-api}}
      CF_ORG: {{cf-org}}
      CF_USER: {{cf-username}}
      CF_PWD: {{cf-password}}
      CF_SPACE: {{cf-space}}
  - task: prepare-app-manifest
    file: cf-test-harness/nodejs/ci/tasks/app-manifest-prep.yml
  - put: cf
    params:
      manifest: app-manifest-output/manifest.yml
      path: cf-test-harness/nodejs/bgd-app

- name: load-tests
  serial: true
  public: true
  plan:
  - get: cf-test-harness
    trigger: true
    passed:
      - deploy-app
  - task: get-current-app-color
    file: cf-test-harness/nodejs/ci/tasks/current-app-get-info.yml
    params:
      CF_API: {{cf-api}}
      CF_ORG: {{cf-org}}
      CF_USER: {{cf-username}}
      CF_PWD: {{cf-password}}
      CF_SPACE: {{cf-space}}
  - task: run-load-tests
    file: cf-test-harness/nodejs/ci/tasks/load-tests.yml
    params:
      CF_APP_DOMAIN: {{cf-app-domain}}

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: cf-test-harness
    trigger: true
    passed:
      - load-tests
  - task: get-current-app-color
    file: cf-test-harness/nodejs/ci/tasks/current-app-get-info.yml
    params:
      CF_API: {{cf-api}}
      CF_ORG: {{cf-org}}
      CF_USER: {{cf-username}}
      CF_PWD: {{cf-password}}
      CF_SPACE: {{cf-space}}
  - task: switch-app-routes
    file: cf-test-harness/nodejs/ci/tasks/update-routes.yml
    params:
      CF_API: {{cf-api}}
      CF_ORG: {{cf-org}}
      CF_USER: {{cf-username}}
      CF_PWD: {{cf-password}}
      CF_SPACE: {{cf-space}}
