---
resources:
  - name: every-5m
    type: time
    source: {interval: 5m}
  - name: pcf-test-harness
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}

  - name: version
    type: semver
    source:
      bucket: {{s3-bucket-version}}
      initial_version: 1.0.0-rc.0
      key: current-version
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: {{s3-endpoint}}

  - name: candidate-release
    type: s3
    source:
      bucket: {{s3-bucket-release-candidates}}
      regexp: pcf-test-java-(.*).war
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: {{s3-endpoint}}

  - name: final-release
    type: s3
    source:
      bucket: {{s3-bucket-releases}}
      regexp: pcf-test-java-(.*).war
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: {{s3-endpoint}}

  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: java-unit-test
    public: true
    plan:
      - get: every-5m
        trigger: true
      - get: pcf-test-harness
        trigger: true
      - task: unit
        file: pcf-test-harness/java/ci/tasks/unit.yml
        params: &MAVENPARAMS
          MAVEN_OPTS: {{maven-opts}}
          MAVEN_CONFIG: {{maven-config}}

  - name: build-artifact
    serial_groups: [ version ]
    plan:
      - get: pcf-test-harness
        passed: [ java-unit-test ]
        trigger: true
      - get: version
        params: { pre: rc }
      - task: build
        file: pcf-test-harness/java/ci/tasks/build.yml
        params:
          <<: *MAVENPARAMS
      - put: candidate-release
        params: { file: build/*.jar }
      - put: version
        params: { file: version/number }

  - name: integration-test
    serial: true
    plan:
      - get: candidate-release
        trigger: true
        passed: [ build-artifact ]
      - get: pcf-test-harness
        passed: [ build-artifact ]
      - get: version
        passed: [ build-artifact ]
      - task: prepare-integration
        file: pcf-test-harness/java/ci/tasks/prepare-integration.yml
        params:
          CF_MANIFEST_HOST: {{cf-manifest-host}}
      - put: cf
        params:
          manifest: prepare-integration/manifest.yml
      - task: integration
        file: pcf-test-harness/java/ci/tasks/integration.yml
        params:
          <<: *MAVENPARAMS

  - name: ship-it
    serial_groups: [ version ]
    plan:
      - get: candidate-release
        passed: [ integration-test ]
      - get: pcf-test-harness
        passed: [ integration-test ]
      - get: version
        params: { bump: final }
      - task: prepare-final
        file: pcf-test-harness/java/ci/tasks/prepare-final.yml
      - put: final-release
        params: { file: prepare-final/*.jar }
      - put: version
        params: { file: version/number }

  - name: major
    serial_groups: [ version ]
    plan:
      - put: version
        params: { bump: major, pre: rc }

  - name: minor
    serial_groups: [ version ]
    plan:
      - put: version
        params: { bump: minor, pre: rc }

  - name: patch
    serial_groups: [ version ]
    plan:
      - get: version
        passed: [ ship-it ]
        trigger: true
      - put: version
        params: { bump: patch, pre: rc }
