---
resources:
  - name: every-5m
    type: time
    source: {interval: 5m}
  - name: cf-test-harness
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}

  - name: version
    type: semver
    source:
      driver: git
      uri: {{gitssh-uri}}
      branch: version
      file: version
      private_key: {{git-repo-private-key}}

  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: unit-test
    public: true
    plan:
      - get: every-5m
        trigger: true
      - get: cf-test-harness
        trigger: true
      - task: unit
        file: cf-test-harness/java/ci/tasks/unit.yml
        params: &MAVENPARAMS
          MAVEN_OPTS: {{maven-opts}}
          MAVEN_CONFIG: {{maven-config}}

  - name: build-it
    serial_groups: [ version ]
    plan:
      - get: cf-test-harness
        passed: [ unit-test ]
        trigger: true
      - get: version
        params: { pre: rc }
      - task: build
        file: cf-test-harness/java/ci/tasks/build.yml
        params:
          <<: *MAVENPARAMS
      - put: cf
        params:
          manifest: cf-test-harness/java/manifest.yml
          current_app_name: canary-java
          path: build/gs-spring-boot-*.jar
      # - put: version
      #   params: { file: version/number }
      # - task: prepare-integration
      #   file: cf-test-harness/java/ci/tasks/prepare-integration.yml
      #   params:
      #     candidate-release: cf-test-harness/java/target/gs-spring-boot-0.1.0.jar


  - name: test-it
    serial_groups: [ version ]
    plan:
      - get: cf-test-harness
        passed: [ build-it ]
        trigger: true
      - task: cf-test
        file: cf-test-harness/java/ci/tasks/cf-test.yml
        params:
          cf_app: canary-java
          cf_app_suffix: {{cf-app-suffix}}
          cf_api: {{cf-api}}
          cf_username: {{cf-username}}
          cf_password: {{cf-password}}
          cf_org: {{cf-org}}
          cf_space: {{cf-space}}
          cf_test_url_endpoint: {{cf-health-endpoint}}
          skip_cert_check: true
  - name: ship-it
    serial_groups: [ version ]
    plan:
      - get: cf-test-harness
        passed: [ test-it ]
        trigger: true
      - get: version
        params: { bump: final }
      - put: version
        params: { file: version/number }
