---
resources:
  - name: every-5m
    type: time
    source: {interval: 5m}
  - name: cf-test-harness
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}

  - name: version
    type: semver
    source:
      driver: git
      uri: {{gitssh-uri}}
      branch: version
      file: version
      private_key: {{git-repo-private-key}}

  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: java-unit-test
    public: true
    plan:
      - get: every-5m
        trigger: true
      - get: cf-test-harness
        trigger: true
      - task: unit
        file: cf-test-harness/java/ci/tasks/unit.yml
        params: &MAVENPARAMS
          MAVEN_OPTS: {{maven-opts}}
          MAVEN_CONFIG: {{maven-config}}

  - name: build-artifact
    serial_groups: [ version ]
    plan:
      - get: cf-test-harness
        passed: [ java-unit-test ]
        trigger: true
      - get: version
        params: { pre: rc }
      - task: build
        file: cf-test-harness/java/ci/tasks/build.yml
        params:
          <<: *MAVENPARAMS
      - put: version
        params: { file: version/number }

  - name: integration-test
    serial: true
    plan:
      - get: cf-test-harness
        passed: [ build-artifact ]
      - get: version
        passed: [ build-artifact ]
      - task: prepare-integration
        file: cf-test-harness/java/ci/tasks/prepare-integration.yml
        params:
          CF_MANIFEST_HOST: {{cf-manifest-host}}
      - put: cf
        params:
          manifest: prepare-integration/manifest.yml
      - task: integration
        file: cf-test-harness/java/ci/tasks/integration.yml
        params:
          <<: *MAVENPARAMS

  - name: ship-it
    serial_groups: [ version ]
    plan:
      - get: version
        params: { bump: final }
      - put: version
        params: { file: version/number }
