---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: pcf-test-harness
  - name: version

outputs:
  - name: build

run:
  path: pcf-test-harness/java/ci/tasks/build.sh
  args: [
    --input-dir, pcf-test-harness/java,
    --output-dir, build,
    --version-file, version/number,
    --artifactId, pcf-demo,
    --packaging, war
  ]
