---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: {{repo-name}}
  - name: version

outputs:
  - name: build

run:
  path: java/ci/tasks/build.sh
  args: [
    --input-dir, {{repo-name}}/java,
    --output-dir, build,
    --version-file, version/number,
    --artifactId, gs-spring-boot,
    --packaging, jar
  ]
