---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: pcf-test-harness

run:
  path: pcf-test-harness/java/ci/tasks/integration.sh
  args: [
    --input-dir, pcf-test-harness/java
  ]
