---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  CF_MANIFEST_HOST:

inputs:
  - name: cf-test-harness
  - name: version

outputs:
  - name: prepare-integration

run:
  path: cf-test-harness/java/ci/tasks/prepare-integration.sh
  args: [
    --input-dir, cf-test-harness/java/target,
    --output-dir, prepare-integration,
    --version-file, version/number,
    --input-manifest, cf-test-harness/java/manifest.yml,
    --artifactId, gs-spring-boot,
    --packaging, jar
  ]
